Lang By Added
savoirfairelinux/num2words pull request #506
Opened 2023-03-21 07:25 UTC by SkiBY

### Changes proposed in this pull request:

Belarusian Language added

### Status

READY

### How to verify this change

Tests are written, but should be checked by another person

### Additional notes

Small change in RU section for currency BYN

2023-03-24 09:56 UTC, veryberry commented on num2words/lang_BY.py
> +    6: 'шастнаццаць',
шаснаццаць

2023-03-24 09:57 UTC, veryberry commented on num2words/lang_BY.py
> +    7: 'семнаццаць',
сямнаццаць

2023-03-24 09:59 UTC, veryberry commented on num2words/lang_BY.py
> +    5: 'пяцьдзясят',
пяцьдзесят

2023-03-24 09:59 UTC, veryberry commented on num2words/lang_BY.py
> +    6: 'шэсцьдзясят',
шэсцьдзесят

2023-03-24 10:06 UTC, veryberry commented on num2words/lang_BY.py
> +        'UZS': (('сум', 'сума', 'сумаў'), ('тыйін', 'тыйіны', 'тыйінаў')),
можа сума -> сумы

2023-03-24 10:07 UTC, veryberry commented on num2words/lang_BY.py
> +            'чатыры': 'чацьвёрты',
чацвёрты ?

2023-03-24 10:08 UTC, veryberry commented on num2words/lang_BY.py
> +            'шесць': 'шасты',
шосты (націск на О)

2023-03-24 10:08 UTC, SkiBY commented on num2words/lang_BY.py
> +    6: 'шэсцьдзясят',
шэсцьдзясят - новыя правiлы

2023-03-24 10:16 UTC, SkiBY commented on num2words/lang_BY.py
> +        'UZS': (('сум', 'сума', 'сумаў'), ('тыйін', 'тыйіны', 'тыйінаў')),
а хто ведае дакладна?...
але сумы гучыць... лепей )

2023-03-24 10:25 UTC, veryberry commented on num2words/lang_BY.py
> +        'UZS': (('сум', 'сума', 'сумаў'), ('тыйін', 'тыйіны', 'тыйінаў')),
калі гэта мужчынскі род (бо такі канчатак) то
1 сум 2 сумы

2023-03-24 13:36 UTC, SkiBY commented
@veryberry please recheck

2023-03-30 05:24 UTC, veryberry approved these changes

2023-03-30 06:58 UTC, veryberry commented
reviewed

2023-03-30 06:59 UTC, veryberry submitted a review, later dismissed
reviewed

2023-03-30 07:03 UTC, SkiBY commented
@mrodriguezg1991 
could you check it please

2023-06-21 08:10 UTC, yorlov commented on num2words/lang_BY.py
> +    8: 'васямнаццаць',
[васемнаццаць](https://ru.wiktionary.org/wiki/%D0%B2%D0%B0%D1%81%D0%B5%D0%BC%D0%BD%D0%B0%D1%86%D1%86%D0%B0%D1%86%D1%8C)

2023-06-21 08:12 UTC, yorlov commented on num2words/lang_BY.py
> +            'шесць': 'шосты',
шэсць

2023-06-21 08:13 UTC, yorlov commented on num2words/lang_BY.py
> +            'девяць': 'дзявяты',
дзевяць

2023-06-21 08:15 UTC, yorlov requested changes

2023-06-21 08:15 UTC, yorlov commented on num2words/lang_BY.py
> +            'шесць': 'шасці',
шэсць

2023-06-21 08:15 UTC, yorlov commented on num2words/lang_BY.py
> +            'дзевяць': 'дзевяті',
дзевяцi

2023-06-21 08:23 UTC, SkiBY commented on num2words/lang_BY.py
> +            'девяць': 'дзявяты',
дзевяць - так, дзявяты па новых правiлах

2023-06-21 17:49 UTC, SkiBY commented
@yorlov updated, corrected, some gender bugs corrected thanks to DD
coverage increased, ready to be approved, I hope

2023-06-21 18:51 UTC, Spaider approved these changes
Denis is here, Belarusian-speaking guy.
This MR looks good to me.

2023-06-21 20:25 UTC, SkiBY commented
@mrodriguezg1991 could you please recheck it?

2023-08-17 09:26 UTC, SkiBY commented
@mrodriguezg1991 could you please approve it?

2023-08-17 16:12 UTC, mrodriguezg1991 commented
> @mrodriguezg1991 could you please approve it?

@SkiBY you need to enable isort and flake validation in order to pass the test, the test for this MR were successful because the validation was removed, once this is solve i will approve, sorry for any inconvenience and thanks for taking the time to contribute to the project

2023-08-17 17:04 UTC, SkiBY commented
> > @mrodriguezg1991 could you please approve it?
> 
> @SkiBY you need to enable isort and flake validation in order to pass the test, the test for this MR were successful because the validation was removed, once this is solve i will approve, sorry for any inconvenience and thanks for taking the time to contribute to the project

reformatted 
flake8 and isort locally passed

2023-10-16 15:23 UTC, SkiBY commented
@mrodriguezg1991 could you please review this PR?

2023-10-16 15:34 UTC, mrodriguezg1991 commented
> @mrodriguezg1991 could you please review this PR?

Hello, Can you please review previous comments? This PR removes the isort and flake8 validation, you need too fix that in order to merge this changes, thanks for taking the time to contribute

2023-10-16 21:23 UTC, SkiBY commented
> > @mrodriguezg1991 could you please review this PR?
> 
> Hello, Can you please review previous comments? This PR removes the isort and flake8 validation, you need too fix that in order to merge this changes, thanks for taking the time to contribute

Sorry @mrodriguezg1991 , I read it in opposite way. 
tox.ini restored

2023-10-17 08:41 UTC, SkiBY commented
@mrodriguezg1991  touched code for re-run - all checks are passed. Probably, yesterday there were problems with Actions?

2023-10-17 13:55 UTC, mrodriguezg1991 approved these changes

2023-10-17 13:57 UTC, merged